/**
 * MD Generator — automated markdown documentation.
 *
 * Scans a project for source files, extracts the API surface (exports,
 * functions, classes, interfaces, doc comments) with lightweight parsers,
 * and writes a markdown doc — fully offline, using the token estimator to
 * report what the doc costs to render. `watchDocs` regenerates periodically.
 */
import { readFileSync } from 'node:fs';
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { BRAND, countTokens } from '@mugil-ide/core';
import { globToRegex, matchesAny } from './glob.js';
import { parseFile, type ParsedFile } from './parse.js';

export { globToRegex, matchesAny } from './glob.js';
export { parseFile } from './parse.js';
export type { DocSymbol, ParsedFile } from './parse.js';

export interface DocsOptions {
  /** Project root to scan. */
  root: string;
  /** Include globs (relative to root). Default: all files. */
  globs?: string[];
  /** Directory names to skip entirely. */
  ignore?: string[];
  /** Output markdown file. Default: <root>/DOCUMENTATION.md */
  output?: string;
}

export interface DocsResult {
  output: string;
  filesScanned: number;
  symbols: number;
  tokens: number;
  bytes: number;
  generatedAt: string;
}

const DEFAULT_IGNORE = ['node_modules', '.git', 'dist', 'coverage', '.cache', 'build'];

async function walkFiles(root: string, globs: RegExp[], ignore: Set<string>): Promise<string[]> {
  const files: string[] = [];
  async function visit(dir: string, relDir: string): Promise<void> {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (ignore.has(entry.name)) continue;
        await visit(path.join(dir, entry.name), path.posix.join(relDir, entry.name));
      } else if (entry.isFile()) {
        const rel = path.posix.join(relDir, entry.name);
        if (matchesAny(rel, globs)) files.push(path.join(dir, entry.name));
      }
    }
  }
  await visit(root, '');
  return files.sort();
}

function readPackageMeta(root: string): { name?: string; description?: string; version?: string } {
  try {
    return JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8')) as {
      name?: string;
      description?: string;
      version?: string;
    };
  } catch {
    return {};
  }
}

function renderTree(rels: string[]): string {
  if (rels.length === 0) return '_(no files matched)_\n';
  let tree = '```\n';
  for (const rel of rels) {
    tree += `${rel}\n`;
  }
  tree += '```\n';
  return tree;
}

function renderModules(parsed: ParsedFile[]): string {
  const withSymbols = parsed.filter((p) => p.symbols.length > 0);
  if (withSymbols.length === 0) return '_(no exported symbols found)_\n';

  const sections: string[] = [];
  for (const file of withSymbols) {
    sections.push(`### \`${file.path}\``);
    for (const symbol of file.symbols) {
      const docs = symbol.docs ? ` — ${symbol.docs}` : '';
      sections.push(`- \`${symbol.signature}\`${docs}`);
    }
    sections.push('');
  }
  return sections.join('\n');
}

async function assembleMarkdown(root: string, rels: string[], parsed: ParsedFile[]): Promise<string> {
  const meta = readPackageMeta(root);
  const generatedAt = new Date().toISOString();
  const lines = [
    `# ${meta.name ?? path.basename(root)} — Documentation`,
    '',
    `> Generated by the ${BRAND} MD Generator on ${generatedAt}.`,
    meta.description ? `>\n> ${meta.description}` : '',
    '',
    '## Overview',
    '',
    `- Files scanned: ${rels.length}`,
    `- Symbols documented: ${parsed.reduce((sum, p) => sum + p.symbols.length, 0)}`,
    `- Estimated tokens to render this doc: ${countTokens(parsed.map((p) => p.symbols.map((s) => s.signature).join('\n')).join('\n'))}`,
    '',
    '## File tree',
    '',
    renderTree(rels),
    '## Modules',
    '',
    renderModules(parsed),
  ];
  return lines.filter((l, i) => !(l === '' && lines[i - 1] === '')).join('\n').trimEnd() + '\n';
}

/** Generates (and writes) the markdown documentation for a project. */
export async function generateDocs(options: DocsOptions): Promise<DocsResult> {
  const root = path.resolve(options.root);
  const globs = (options.globs ?? ['**/*']).map(globToRegex);
  const ignore = new Set(options.ignore ?? DEFAULT_IGNORE);
  const output = options.output ? path.resolve(options.output) : path.join(root, 'DOCUMENTATION.md');

  const files = await walkFiles(root, globs, ignore);
  const parsed: ParsedFile[] = [];
  const rels: string[] = [];
  for (const file of files) {
    try {
      const rel = path.relative(root, file).split(path.sep).join('/');
      rels.push(rel);
      const content = await fs.readFile(file, 'utf8');
      parsed.push(parseFile(rel, content));
    } catch {
      // Skip unreadable/binary files.
    }
  }

  const markdown = await assembleMarkdown(root, rels, parsed);
  await fs.mkdir(path.dirname(output), { recursive: true });
  await fs.writeFile(output, markdown, 'utf8');

  return {
    output,
    filesScanned: files.length,
    symbols: parsed.reduce((sum, p) => sum + p.symbols.length, 0),
    tokens: countTokens(markdown),
    bytes: Buffer.byteLength(markdown, 'utf8'),
    generatedAt: new Date().toISOString(),
  };
}

export interface WatchDocsOptions extends DocsOptions {
  intervalSeconds: number;
  onGenerated?: (result: DocsResult) => void;
  onError?: (error: unknown) => void;
  signal?: AbortSignal;
}

/** Regenerates the documentation periodically. */
export function watchDocs(options: WatchDocsOptions): { stop(): void } {
  const tick = async (): Promise<void> => {
    const result = await generateDocs(options);
    options.onGenerated?.(result);
  };
  void tick().catch((err) => options.onError?.(err));
  const handle = setInterval(() => {
    void tick().catch((err) => options.onError?.(err));
  }, Math.max(1, options.intervalSeconds) * 1000);
  const stop = (): void => clearInterval(handle);
  options.signal?.addEventListener('abort', stop, { once: true });
  return { stop };
}
