import { stripCodeSignatures, stripSignatures } from '../src/modules/signature-remover/index.js';

describe('stripSignatures (prompt side)', () => {
  it('strips Anthropic system tag and Human marker', () => {
    const input = '<system>You are Claude, a helpful assistant.</system>\nHuman: Write a parser.';
    const { text, removed } = stripSignatures(input, { providers: ['anthropic'] });
    expect(text).toContain('Write a parser');
    expect(text).not.toContain('<system>');
    expect(text).not.toContain('Human:');
    expect(removed.length).toBeGreaterThan(0);
  });

  it('strips OpenAI identity preamble', () => {
    const input = 'As an AI language model, I can help you with that. Explain recursion.';
    const { text } = stripSignatures(input, { providers: ['openai'] });
    expect(text).toContain('Explain recursion');
    expect(text).not.toMatch(/as an ai language model/i);
  });

  it('strips generic closers across providers', () => {
    const input = 'Fix the memory leak. Thanks in advance for your help!';
    const { text } = stripSignatures(input);
    expect(text).toContain('Fix the memory leak');
    expect(text).not.toMatch(/thanks in advance/i);
  });

  it('leaves clean prompts alone', () => {
    const input = 'Implement a red-black tree in TypeScript.';
    const { text, changed } = stripSignatures(input);
    expect(changed).toBe(false);
    expect(text).toBe(input);
  });

  it('reports what was removed for debugging', () => {
    const { removed } = stripSignatures('Please review. Thank you in advance!');
    expect(removed.some((r) => r.includes('gratitude'))).toBe(true);
  });
});

describe('stripCodeSignatures (code side)', () => {
  it('removes an AI-generated header block', () => {
    const code = `// Generated by Copilot
// This file was created automatically
export function add(a: number, b: number) {
  return a + b;
}`;
    const { text, removed } = stripCodeSignatures(code);
    expect(text).toContain('export function add');
    expect(text).not.toMatch(/generated by/i);
    expect(removed.some((r) => r.includes('generated-header'))).toBe(true);
  });

  it('removes AI-attribution comment lines anywhere', () => {
    const code = `export function fib(n: number): number {
  // This code was generated by ChatGPT
  return n < 2 ? n : fib(n - 1) + fib(n - 2);
}`;
    const { text } = stripCodeSignatures(code);
    expect(text).not.toMatch(/chatgpt/i);
    expect(text).toContain('fib');
  });

  it('removes invisible watermark characters', () => {
    const code = 'export const x = 1;\u200B\u200D\uFEFF';
    const { text, removed } = stripCodeSignatures(code);
    expect(text).toBe('export const x = 1;');
    expect(removed.some((r) => r.includes('watermark'))).toBe(true);
  });

  it('leaves clean code untouched', () => {
    const code = 'export const sum = (a: number, b: number) => a + b;';
    const { text, changed } = stripCodeSignatures(code);
    expect(changed).toBe(false);
    expect(text).toContain('sum');
  });
});
