import { stripWatermarks } from '../src/modules/watermark-remover/index.js';

describe('stripWatermarks (Layer A unicode)', () => {
  it('removes zero-width carriers and BOM', () => {
    const input = 'hello\u200B world\u200D\u2060\uFEFF';
    const { text, removed } = stripWatermarks(input);
    expect(text).toBe('hello world');
    expect(removed.some((r) => r.includes('unicode:invisible'))).toBe(true);
  });

  it('removes soft hyphens', () => {
    const { text } = stripWatermarks('pass\u00ADword');
    expect(text).toBe('password');
  });

  it('removes bidi controls', () => {
    const input = 'left\u202Eright\u2066x\u2069';
    const { text } = stripWatermarks(input);
    expect(text).toBe('leftrightx');
  });

  it('removes tag characters', () => {
    const { text, removed } = stripWatermarks('abc\u{E0001}\u{E007F}def');
    expect(text).toBe('abcdef');
    expect(removed.some((r) => r.includes('unicode:tag'))).toBe(true);
  });

  it('normalizes exotic spaces to a regular space', () => {
    const input = 'a\u00A0b\u2003c\u3000d';
    const { text } = stripWatermarks(input);
    expect(text).toBe('a b c d');
  });
});

describe('stripWatermarks (vendor attribution lines)', () => {
  it('removes an OpenAI attribution line', () => {
    const input = 'This response was generated by AI.\nHere is the actual content.';
    const { text, removed } = stripWatermarks(input);
    expect(text).toBe('Here is the actual content.');
    expect(removed.some((r) => r.includes('openai:attribution-line'))).toBe(true);
  });

  it('removes an Anthropic attribution line', () => {
    const input = 'Written by Claude.\nReal answer follows.';
    const { text } = stripWatermarks(input);
    expect(text).toBe('Real answer follows.');
  });

  it('removes a Gemini/SynthID stamp', () => {
    const input = 'This text was produced with Gemini.\nKeep this.';
    const { text } = stripWatermarks(input);
    expect(text).toBe('Keep this.');
  });

  it('can restrict vendor providers via options', () => {
    const input = 'This response was generated by AI.\nWritten by Claude.';
    const { text } = stripWatermarks(input, { providers: ['openai'] });
    expect(text).not.toContain('generated by AI');
    expect(text).toContain('Written by Claude');
  });

  it('can restrict to the unicode layer only', () => {
    const input = 'a\u200Bb\nThis response was generated by AI.';
    const { text } = stripWatermarks(input, { layers: ['unicode'] });
    expect(text).toBe('ab\nThis response was generated by AI.');
  });
});

describe('stripWatermarks (hygiene)', () => {
  it('leaves clean text untouched', () => {
    const input = 'Implement a red-black tree in TypeScript.';
    const { text, changed } = stripWatermarks(input);
    expect(changed).toBe(false);
    expect(text).toBe(input);
  });

  it('reports what was removed', () => {
    const { removed } = stripWatermarks('hello\u200B world\nThis response was created by an AI assistant.');
    expect(removed.some((r) => r.includes('unicode'))).toBe(true);
    expect(removed.some((r) => r.includes('attribution-line'))).toBe(true);
  });
});
