import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createMcpServer } from '../src/server.js';
import { createEngine, loadConfig } from '@mugil-ide/core';

type ToolResult = {
  content?: Array<{ type?: string; text?: string }>;
  isError?: boolean;
};

async function toolResultText(result: ToolResult): Promise<string> {
  const text = result.content?.[0]?.text ?? '';
  return text;
}

describe('Mugil IDE MCP server', () => {
  let client: Client;

  beforeAll(async () => {
    const engine = createEngine(loadConfig()); // NODE_ENV=test -> hermetic memory cache
    const server = createMcpServer(engine);
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    await server.connect(serverTransport);
    client = new Client({ name: 'test-client', version: '0.0.1' });
    await client.connect(clientTransport);
  });

  afterAll(async () => {
    await client.close();
  });

  it('exposes the expected tool set', async () => {
    const { tools } = await client.listTools();
    const names = tools.map((t) => t.name).sort();
    expect(names).toEqual(
      expect.arrayContaining([
        'ask',
        'caveman',
        'codegraph',
        'codegraph_relevant',
        'compress_command_output',
        'count_tokens',
        'list_models',
        'refine_prompt',
        'rtk',
        'strip_code_signatures',
        'strip_signatures',
        'strip_watermarks',
      ]),
    );
  });

  it('counts tokens', async () => {
    const res = (await client.callTool({
      name: 'count_tokens',
      arguments: { text: 'hello world' },
    })) as ToolResult;
    const parsed = JSON.parse(await toolResultText(res)) as { tokens: number };
    expect(parsed.tokens).toBeGreaterThan(0);
  });

  it('refines a prompt and reports savings', async () => {
    const res = (await client.callTool({
      name: 'refine_prompt',
      arguments: {
        prompt: 'Hi there! In order to fix the bug, please kindly review the code. Thanks in advance!',
      },
    })) as ToolResult;
    const parsed = JSON.parse(await toolResultText(res)) as {
      originalTokens: number;
      refinedTokens: number;
      appliedStrategies: string[];
    };
    expect(parsed.refinedTokens).toBeLessThanOrEqual(parsed.originalTokens);
    expect(parsed.appliedStrategies.length).toBeGreaterThan(0);
  });

  it('strips prompt and code signatures', async () => {
    const promptRes = (await client.callTool({
      name: 'strip_signatures',
      arguments: { text: '<system>You are Claude.</system> Human: Write a parser.' },
    })) as ToolResult;
    const promptOut = JSON.parse(await toolResultText(promptRes)) as { text: string };
    expect(promptOut.text).toContain('Write a parser');
    expect(promptOut.text).not.toContain('Human:');

    const codeRes = (await client.callTool({
      name: 'strip_code_signatures',
      arguments: { code: '// Generated by Copilot\nexport const x = 1;' },
    })) as ToolResult;
    const codeOut = JSON.parse(await toolResultText(codeRes)) as { text: string };
    expect(codeOut.text).toContain('export const x');
    expect(codeOut.text).not.toMatch(/generated by/i);
  });

  it('compresses command output', async () => {
    const res = (await client.callTool({
      name: 'compress_command_output',
      arguments: { output: 'ok\nok\nok\ndone' },
    })) as ToolResult;
    const out = JSON.parse(await toolResultText(res)) as { text: string };
    expect(out.text).toContain('3×');
  });

  it('runs the full pipeline via ask (mock mode)', async () => {
    const res = (await client.callTool({
      name: 'ask',
      arguments: { prompt: 'In order to write a parser, please help. Thanks!' },
    })) as ToolResult;
    const out = JSON.parse(await toolResultText(res)) as {
      response: string;
      model: string;
      mock: boolean;
      refine: { savingsPct: number };
      cache: { hit: boolean };
    };
    expect(out.response.length).toBeGreaterThan(0);
    expect(out.mock).toBe(true);
    expect(out.model).toBeTruthy();
  });

  it('lists the model ladder', async () => {
    const res = (await client.callTool({ name: 'list_models', arguments: {} })) as ToolResult;
    const models = JSON.parse(await toolResultText(res)) as Array<{
      id: string;
      contextWindow: number;
    }>;
    expect(models.length).toBeGreaterThan(0);
    expect(models[0]?.id).toBeTruthy();
    expect(models[0]?.contextWindow).toBeGreaterThan(0);
  });

  it('applies single strategies (caveman, rtk)', async () => {
    const caveman = (await client.callTool({
      name: 'caveman',
      arguments: { prompt: 'In order to fix it, please review.' },
    })) as ToolResult;
    const cavemanOut = JSON.parse(await toolResultText(caveman)) as { text: string };
    expect(cavemanOut.text).not.toContain('In order to');

    const rtk = (await client.callTool({
      name: 'rtk',
      arguments: { prompt: 'Refactor the parser. Refactor the parser. Refactor the parser.' },
    })) as ToolResult;
    const rtkOut = JSON.parse(await toolResultText(rtk)) as { text: string };
    expect(rtkOut.text.match(/refactor the parser/gi)?.length).toBe(1);
  });
});
