/**
 * WATERMARK REMOVER MODULE
 * ========================
 * Removes AI provenance watermarks from generated text — the invisible
 * carriers vendors hide in the character stream, plus the visible
 * attribution lines they stamp on content.
 *
 * Credits
 * -------
 * Inspired by **guillaumemeyer/watermarks-remover**
 * (https://github.com/guillaumemeyer/watermarks-remover) — an agent skill +
 * Python scripts that strip multi-vendor AI provenance marks from text and
 * files. This module ports its deterministic **Layer A** (Unicode text
 * hygiene) to TypeScript:
 *
 *   - **Invisible carriers** — zero-width space (U+200B), zero-width
 *     non-joiner/joiner (U+200C/U+200D), word joiner (U+2060), BOM /
 *     zero-width no-break space (U+FEFF), soft hyphen (U+00AD).
 *   - **Bidi / format controls** — U+202A–U+202E, U+2066–U+2069, Arabic
 *     letter mark (U+061C) — used to reorder rendered text invisibly.
 *   - **Tag characters** — U+E0000–U+E007F (deprecated tag block).
 *   - **Exotic spaces** — U+00A0, U+1680, U+2000–U+200A, U+202F, U+205F,
 *     U+3000 — normalized to a regular space.
 *   - **Vendor attribution lines** — "This response was generated by AI",
 *     "Written by Claude", "Powered by ChatGPT", Gemini/SynthID stamps.
 *
 * **Layer B** (statistical token-sampling watermarks — SynthID-Text,
 * Kirchenbauer-style) cannot be removed deterministically: the signal lives
 * in the token choices themselves, so removal means rewriting a substantial
 * fraction of the text. That is a best-effort model rewrite pass, not a
 * regex — out of scope here; see the module README.
 *
 * Responsible use: this is for content you own or are authorized to process
 * (privacy/hygiene), not for fraud or false "human-written" claims. No tool
 * can certify that a vendor's detector will fail.
 *
 * All patterns live in `src/rules/watermark-remover.json` and are updatable
 * at runtime via `mugil-ide update` (see src/modules/overrides.ts).
 *
 * See ATTRIBUTIONS.md at the repository root for the full credit list.
 */

import type { StrategyResult } from '../../types.js';
import defaultRules from '../../rules/watermark-remover.json';
import { currentRevision, loadRulesSync } from '../overrides.js';

export type WatermarkProvider = 'openai' | 'anthropic' | 'gemini';

interface UnicodeRuleSpec {
  label: string;
  pattern?: string;
  flags?: string;
  /** Codepoint ranges (inclusive) — used for supplementary-plane blocks that
   * cannot be expressed as a regex character-class range (V8 rejects
   * `\u{...}` range endpoints in classes). */
  ranges?: Array<[number, number]>;
}

interface VendorRuleSpec {
  provider: WatermarkProvider;
  label: string;
  pattern: string;
  flags?: string;
}

interface WatermarkRules {
  version: string;
  unicode: {
    invisible: UnicodeRuleSpec;
    bidi: UnicodeRuleSpec;
    tags: UnicodeRuleSpec;
    exoticSpaces: UnicodeRuleSpec;
  };
  vendor: VendorRuleSpec[];
}

interface CompiledRules {
  unicode: Array<{
    label: string;
    regex?: RegExp;
    ranges?: Array<[number, number]>;
    normalizeToSpace: boolean;
  }>;
  vendor: Array<{ provider: WatermarkProvider; label: string; regex: RegExp }>;
}

let compiled: CompiledRules | undefined;
let compiledAt = -1;

function getRules(): CompiledRules {
  const revision = currentRevision();
  if (!compiled || compiledAt !== revision) {
    const doc = loadRulesSync<WatermarkRules>(
      'watermark-remover',
      defaultRules as unknown as WatermarkRules,
    );
    const unicodeRule = (
      spec: UnicodeRuleSpec,
      normalizeToSpace: boolean,
    ): CompiledRules['unicode'][number] => ({
      label: spec.label,
      regex: spec.pattern ? new RegExp(spec.pattern, spec.flags ?? 'g') : undefined,
      ranges: spec.ranges,
      normalizeToSpace,
    });
    compiled = {
      unicode: [
        unicodeRule(doc.unicode.invisible, false),
        unicodeRule(doc.unicode.bidi, false),
        unicodeRule(doc.unicode.tags, false),
        unicodeRule(doc.unicode.exoticSpaces, true),
      ],
      vendor: doc.vendor.map((r) => ({
        provider: r.provider,
        label: r.label,
        regex: new RegExp(r.pattern, r.flags ?? 'gim'),
      })),
    };
    compiledAt = revision;
  }
  return compiled;
}

export interface StripWatermarkOptions {
  /** Restrict stripping to specific layers ('unicode' | 'vendor'). */
  layers?: Array<'unicode' | 'vendor'>;
  /** Restrict vendor-line stripping to specific providers. */
  providers?: WatermarkProvider[];
}

/**
 * Removes AI provenance watermarks from generated text (Layer A, deterministic).
 * Returns the cleaned text plus the list of removed watermark carriers/marks.
 */
export function stripWatermarks(text: string, options: StripWatermarkOptions = {}): StrategyResult {
  const { unicode, vendor } = getRules();
  const layers = new Set(options.layers ?? (['unicode', 'vendor'] as const));
  const providers = new Set(options.providers ?? (['openai', 'anthropic', 'gemini'] as WatermarkProvider[]));
  const removed: string[] = [];
  let out = text;

  if (layers.has('unicode')) {
    for (const rule of unicode) {
      if (rule.ranges) {
        let count = 0;
        let cleaned = '';
        for (const ch of out) {
          const cp = ch.codePointAt(0)!;
          const hit = rule.ranges.some(([start, end]) => cp >= start && cp <= end);
          if (hit) {
            count += 1;
            if (rule.normalizeToSpace) cleaned += ' ';
          } else {
            cleaned += ch;
          }
        }
        if (count > 0) {
          removed.push(`[${rule.label}] ${count} character(s)`);
          out = cleaned;
        }
        continue;
      }
      const count = (out.match(rule.regex!) ?? []).length;
      if (count > 0) {
        removed.push(`[${rule.label}] ${count} character(s)`);
        out = out.replace(rule.regex!, rule.normalizeToSpace ? ' ' : '');
      }
    }
  }

  if (layers.has('vendor')) {
    for (const rule of vendor) {
      if (!providers.has(rule.provider)) continue;
      out = out.replace(rule.regex, (match) => {
        removed.push(`[${rule.label}] ${match.trim().slice(0, 120)}`);
        return '';
      });
    }
  }

  out = out.replace(/[ \t]{2,}/g, ' ').replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
  return { text: out, changed: out !== text.trim(), removed };
}
